/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockPerformanceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDriverValue"
      | "getPerformanceScore"
      | "setDriverScore"
      | "setDriverValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getDriverValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPerformanceScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDriverScore",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDriverValue",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDriverValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPerformanceScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDriverScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDriverValue",
    data: BytesLike
  ): Result;
}

export interface MockPerformanceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MockPerformanceOracle;
  waitForDeployment(): Promise<this>;

  interface: MockPerformanceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDriverValue: TypedContractMethod<
    [driverId: BigNumberish],
    [bigint],
    "view"
  >;

  getPerformanceScore: TypedContractMethod<
    [driverId: BigNumberish],
    [bigint],
    "view"
  >;

  setDriverScore: TypedContractMethod<
    [driverId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDriverValue: TypedContractMethod<
    [driverId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDriverValue"
  ): TypedContractMethod<[driverId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPerformanceScore"
  ): TypedContractMethod<[driverId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDriverScore"
  ): TypedContractMethod<
    [driverId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDriverValue"
  ): TypedContractMethod<
    [driverId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
