/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockPythInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMockUpdateFee"
      | "getUpdateFee"
      | "setMockUpdateFee"
      | "updatePriceFeeds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMockUpdateFee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateFee",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMockUpdateFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeeds",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMockUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMockUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeeds",
    data: BytesLike
  ): Result;
}

export interface MockPyth extends BaseContract {
  connect(runner?: ContractRunner | null): MockPyth;
  waitForDeployment(): Promise<this>;

  interface: MockPythInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMockUpdateFee: TypedContractMethod<
    [priceFeedId: BytesLike],
    [bigint],
    "view"
  >;

  getUpdateFee: TypedContractMethod<
    [priceUpdateData: BytesLike[]],
    [bigint],
    "view"
  >;

  setMockUpdateFee: TypedContractMethod<
    [priceFeedId: BytesLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePriceFeeds: TypedContractMethod<
    [priceUpdateData: BytesLike[]],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMockUpdateFee"
  ): TypedContractMethod<[priceFeedId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUpdateFee"
  ): TypedContractMethod<[priceUpdateData: BytesLike[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMockUpdateFee"
  ): TypedContractMethod<
    [priceFeedId: BytesLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePriceFeeds"
  ): TypedContractMethod<[priceUpdateData: BytesLike[]], [void], "payable">;

  filters: {};
}
