/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PerformanceOracle {
  export type PerformanceDataStruct = {
    raceId: BigNumberish;
    lapTime: BigNumberish;
    avgSpeed: BigNumberish;
    position: BigNumberish;
    overtakes: BigNumberish;
    points: BigNumberish;
    consistencyScore: BigNumberish;
    timestamp: BigNumberish;
    verified: boolean;
  };

  export type PerformanceDataStructOutput = [
    raceId: bigint,
    lapTime: bigint,
    avgSpeed: bigint,
    position: bigint,
    overtakes: bigint,
    points: bigint,
    consistencyScore: bigint,
    timestamp: bigint,
    verified: boolean
  ] & {
    raceId: bigint;
    lapTime: bigint;
    avgSpeed: bigint;
    position: bigint;
    overtakes: bigint;
    points: bigint;
    consistencyScore: bigint;
    timestamp: bigint;
    verified: boolean;
  };
}

export interface PerformanceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addValidPriceFeed"
      | "authorizedUpdaters"
      | "driverMarketValue"
      | "driverPerformance"
      | "driverPerformanceScore"
      | "getDriverValue"
      | "getPerformanceScore"
      | "getRacePerformance"
      | "owner"
      | "pyth"
      | "recordPerformance"
      | "renounceOwnership"
      | "setAuthorizedUpdater"
      | "transferOwnership"
      | "updatePerformanceViaPyth"
      | "updatePythAddress"
      | "validPriceFeeds"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketValueCalculated"
      | "OwnershipTransferred"
      | "PerformanceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addValidPriceFeed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedUpdaters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "driverMarketValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "driverPerformance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "driverPerformanceScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDriverValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPerformanceScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRacePerformance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordPerformance",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedUpdater",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePerformanceViaPyth",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePythAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validPriceFeeds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addValidPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUpdaters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "driverMarketValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "driverPerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "driverPerformanceScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDriverValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPerformanceScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRacePerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordPerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePerformanceViaPyth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePythAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validPriceFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace MarketValueCalculatedEvent {
  export type InputTuple = [
    driverId: BigNumberish,
    oldValue: BigNumberish,
    newValue: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    driverId: bigint,
    oldValue: bigint,
    newValue: bigint,
    reason: string
  ];
  export interface OutputObject {
    driverId: bigint;
    oldValue: bigint;
    newValue: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceUpdatedEvent {
  export type InputTuple = [
    driverId: BigNumberish,
    raceId: BigNumberish,
    newMarketValue: BigNumberish,
    performanceScore: BigNumberish
  ];
  export type OutputTuple = [
    driverId: bigint,
    raceId: bigint,
    newMarketValue: bigint,
    performanceScore: bigint
  ];
  export interface OutputObject {
    driverId: bigint;
    raceId: bigint;
    newMarketValue: bigint;
    performanceScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PerformanceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PerformanceOracle;
  waitForDeployment(): Promise<this>;

  interface: PerformanceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addValidPriceFeed: TypedContractMethod<
    [priceFeedId: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizedUpdaters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  driverMarketValue: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  driverPerformance: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        raceId: bigint;
        lapTime: bigint;
        avgSpeed: bigint;
        position: bigint;
        overtakes: bigint;
        points: bigint;
        consistencyScore: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  driverPerformanceScore: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getDriverValue: TypedContractMethod<
    [driverId: BigNumberish],
    [bigint],
    "view"
  >;

  getPerformanceScore: TypedContractMethod<
    [driverId: BigNumberish],
    [bigint],
    "view"
  >;

  getRacePerformance: TypedContractMethod<
    [driverId: BigNumberish, raceId: BigNumberish],
    [PerformanceOracle.PerformanceDataStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pyth: TypedContractMethod<[], [string], "view">;

  recordPerformance: TypedContractMethod<
    [
      driverId: BigNumberish,
      raceId: BigNumberish,
      lapTime: BigNumberish,
      avgSpeed: BigNumberish,
      position: BigNumberish,
      overtakes: BigNumberish,
      points: BigNumberish,
      consistencyScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedUpdater: TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePerformanceViaPyth: TypedContractMethod<
    [
      driverId: BigNumberish,
      raceId: BigNumberish,
      priceUpdateData: BytesLike[]
    ],
    [void],
    "payable"
  >;

  updatePythAddress: TypedContractMethod<
    [_pythContract: AddressLike],
    [void],
    "nonpayable"
  >;

  validPriceFeeds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addValidPriceFeed"
  ): TypedContractMethod<[priceFeedId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedUpdaters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "driverMarketValue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "driverPerformance"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        raceId: bigint;
        lapTime: bigint;
        avgSpeed: bigint;
        position: bigint;
        overtakes: bigint;
        points: bigint;
        consistencyScore: bigint;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "driverPerformanceScore"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDriverValue"
  ): TypedContractMethod<[driverId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPerformanceScore"
  ): TypedContractMethod<[driverId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRacePerformance"
  ): TypedContractMethod<
    [driverId: BigNumberish, raceId: BigNumberish],
    [PerformanceOracle.PerformanceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pyth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordPerformance"
  ): TypedContractMethod<
    [
      driverId: BigNumberish,
      raceId: BigNumberish,
      lapTime: BigNumberish,
      avgSpeed: BigNumberish,
      position: BigNumberish,
      overtakes: BigNumberish,
      points: BigNumberish,
      consistencyScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedUpdater"
  ): TypedContractMethod<
    [updater: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePerformanceViaPyth"
  ): TypedContractMethod<
    [
      driverId: BigNumberish,
      raceId: BigNumberish,
      priceUpdateData: BytesLike[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updatePythAddress"
  ): TypedContractMethod<[_pythContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validPriceFeeds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "MarketValueCalculated"
  ): TypedContractEvent<
    MarketValueCalculatedEvent.InputTuple,
    MarketValueCalculatedEvent.OutputTuple,
    MarketValueCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceUpdated"
  ): TypedContractEvent<
    PerformanceUpdatedEvent.InputTuple,
    PerformanceUpdatedEvent.OutputTuple,
    PerformanceUpdatedEvent.OutputObject
  >;

  filters: {
    "MarketValueCalculated(uint256,uint256,uint256,string)": TypedContractEvent<
      MarketValueCalculatedEvent.InputTuple,
      MarketValueCalculatedEvent.OutputTuple,
      MarketValueCalculatedEvent.OutputObject
    >;
    MarketValueCalculated: TypedContractEvent<
      MarketValueCalculatedEvent.InputTuple,
      MarketValueCalculatedEvent.OutputTuple,
      MarketValueCalculatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PerformanceUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      PerformanceUpdatedEvent.InputTuple,
      PerformanceUpdatedEvent.OutputTuple,
      PerformanceUpdatedEvent.OutputObject
    >;
    PerformanceUpdated: TypedContractEvent<
      PerformanceUpdatedEvent.InputTuple,
      PerformanceUpdatedEvent.OutputTuple,
      PerformanceUpdatedEvent.OutputObject
    >;
  };
}
